LANGUAGE_CONFIGURATION = {
    'azz': {
        'parts_of_speech': [
            "Adj",
            "Adv",
            "Aux",
            "Bebe",
            "Clítico",
            "Conjunc",
            "Copula",
            "Demostrativo",
            "Direccional",
            "Estativo",
            "Interj",
            "Interrogativo",
            "Locativo",
            "Modal",
            "Muletilla",
            "Neg",
            "Prefijo",
            "Preposición",
            "Pronombre",
            "Saludo",
            "Subord",
            "Sufijo",
            "Sust",
            "Terminación aspectual",
            "Topónimo",
            "V0",
            "V1",
            "V2",
            "V3",
            "V4",
            "Vocativo",
        ]
    }
}
