# Generated by Django 3.0.5 on 2020-07-12 15:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailtrans', '0009_create_initial_language'),
        ('mesolex_site', '0002_searchpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LanguageHomePage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('language_code', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('sub_headline', models.CharField(max_length=255)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('header_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
    ]
