# Generated by Django 3.0.7 on 2020-08-15 13:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mesolex_site', '0002_auto_20200725_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagehomepage',
            name='search',
        ),
        migrations.AddField(
            model_name='homepage',
            name='language_family_menu',
            field=wagtail.core.fields.StreamField([('language_families', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(required=False)), ('language_families', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('languages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('language_page', wagtail.core.blocks.PageChooserBlock(page_type=['mesolex_site.LanguageHomePage']))])))])))]))], blank=True),
        ),
    ]
