# Generated by Django 3.0.7 on 2020-08-23 13:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mesolex_site', '0003_auto_20200815_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
