# Generated by Django 3.0.5 on 2020-07-25 18:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('mesolex_site', '0005_auto_20200719_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLanguageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('short_name', models.CharField(blank=True, max_length=128)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('sub_headline', models.CharField(blank=True, max_length=255)),
                ('header_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_links', to='mesolex_site.HomePage')),
                ('language_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mesolex_site.LanguageHomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
