# Generated by Django 3.0.7 on 2020-11-24 14:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mesolex_site', '0005_auto_20201011_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='language_family_menu',
            field=wagtail.core.fields.StreamField([('language_families', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(required=False)), ('language_families', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('languages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('language_page', wagtail.core.blocks.PageChooserBlock(page_type=['mesolex_site.LanguageHomePage'], required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))])))])))]))], blank=True),
        ),
    ]
