# Generated by Django 3.0.7 on 2021-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesolex_site', '0006_auto_20201124_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchpage',
            old_name='language_code',
            new_name='dataset_code',
        ),
    ]
