# Generated by Django 3.2.7 on 2021-10-10 16:57

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension


class Migration(migrations.Migration):

    run_before = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
    ]
