# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 21:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LexicalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, verbose_name='Unique ID')),
                ('headword', models.CharField(max_length=256, verbose_name='Headword')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Lexical Entry',
                'verbose_name_plural': 'Lexical Entries',
                'ordering': ('headword',),
            },
        ),
    ]
