# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_auto_20180517_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexCitationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.LexicalEntry')),
            ],
        ),
    ]
