# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_lexcitationform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexcitationform',
            name='entry',
        ),
        migrations.DeleteModel(
            name='LexCitationForm',
        ),
    ]
