# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0006_auto_20180825_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lexicalentrytei',
            name='geo',
        ),
        migrations.AddField(
            model_name='geo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.LexicalEntryTEI'),
        ),
    ]
