# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0007_delete_lexicalentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LexicalEntryTEI',
            new_name='LexicalEntry',
        ),
    ]
