# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0007_auto_20180825_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.TextField(),
        ),
    ]
