# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0008_auto_20180905_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('mime_type', models.CharField(default='audio/mpeg', max_length=64)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.Citation')),
            ],
        ),
    ]
