# Generated by Django 2.1.3 on 2018-11-08 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0009_citationmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonNativeEtymology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.LexicalEntry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
