# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0010_auto_20180826_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='geo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='quote',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pointers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
