# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 14:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0011_auto_20180826_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='pointers',
        ),
        migrations.AddField(
            model_name='example',
            name='pointers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
