# Generated by Django 2.2 on 2019-08-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0011_auto_20190125_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='ostentive',
            field=models.TextField(blank=True),
        ),
    ]
