# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0012_auto_20180826_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflectionaltype',
            name='grammar_group',
        ),
        migrations.RemoveField(
            model_name='partofspeech',
            name='grammar_group',
        ),
        migrations.AddField(
            model_name='sense',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sense',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='InflectionalType',
        ),
        migrations.DeleteModel(
            name='PartOfSpeech',
        ),
    ]
