# Generated by Django 2.2.9 on 2020-02-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0012_sense_ostentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalentry',
            name='language',
            field=models.CharField(default='azz', max_length=64, verbose_name='Lengua'),
            preserve_default=False,
        ),
    ]
