# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0013_auto_20180826_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='translation_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon.Quote'),
        ),
    ]
