# Generated by Django 3.0.7 on 2020-12-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0015_auto_20201213_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='example',
            name='sense',
        ),
        migrations.RemoveField(
            model_name='geo',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='gloss',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='grammargroup',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='nonnativeetymology',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='note',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='example',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='translation_of',
        ),
        migrations.RemoveField(
            model_name='root',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='sense',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Geo',
        ),
        migrations.DeleteModel(
            name='Gloss',
        ),
        migrations.DeleteModel(
            name='GrammarGroup',
        ),
        migrations.DeleteModel(
            name='LexicalEntry',
        ),
        migrations.DeleteModel(
            name='NonNativeEtymology',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Root',
        ),
        migrations.DeleteModel(
            name='Sense',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
