# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0015_auto_20180904_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
