# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0016_root_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
