# Generated by Django 3.0.7 on 2021-01-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0016_auto_20201213_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='other_data',
            new_name='data',
        ),
    ]
