# Generated by Django 3.0.7 on 2021-03-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0017_auto_20210110_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='longsearchablestring',
            options={'verbose_name': 'Searchable String'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media File Link'},
        ),
        migrations.AlterModelOptions(
            name='searchablestring',
            options={'verbose_name': 'Searchable String'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='language',
            new_name='dataset',
        ),
    ]
