# Generated by Django 3.0.7 on 2021-03-21 14:07

from django.db import migrations


def update_dataset_value(apps, _schema_editor):
    Entry = apps.get_model('lexicon', 'Entry')
    Entry.objects.filter(dataset='juxt1235').update(dataset='juxt1235_verb')


def revert_dataset_value_change(apps, schema_editor):
    Entry = apps.get_model('lexicon', 'Entry')
    Entry.objects.filter(dataset='juxt1235_verb').update(dataset='juxt1235')


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0018_auto_20210321_1357'),
    ]

    operations = [
        migrations.RunPython(
            update_dataset_value,
            revert_dataset_value_change,
        ),
    ]
