# Generated by Django 3.0.7 on 2021-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0019_migrate_juxt1235_to_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='identifier',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
