# Generated by Django 3.0.7 on 2021-04-04 12:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0020_auto_20210401_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchablestring',
            options={},
        ),
        migrations.AddIndex(
            model_name='searchablestring',
            index=django.contrib.postgres.indexes.GinIndex(fields=['value'], name='ss_value_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='searchablestring',
            index=django.contrib.postgres.indexes.GinIndex(fields=['type_tag'], name='ss_type_tag_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
