---
- src: https://github.com/caktus/tequila-common
  version: v0.8.9
  name: tequila-common

- src: https://github.com/caktus/tequila-postgresql
  version: v0.8.0
  name: tequila-postgresql

- src: https://github.com/caktus/tequila-nginx
  version: v0.8.9
  name: tequila-nginx

- src: https://github.com/caktus/tequila-django
  version: v0.9.18
  name: tequila-django

- src: geerlingguy.nodejs
  version: 4.2.2
  name: nodejs

- src: https://github.com/caktus/tequila-nodejs
  version: v0.8.1
  name: tequila-nodejs
