---
- src: https://github.com/caktus/tequila-common
  version: v0.8.8
  name: tequila-common

- src: https://github.com/caktus/tequila-postgresql
  version: v0.8.0
  name: tequila-postgresql

- src: https://github.com/caktus/tequila-nginx
  version: v0.8.0
  name: tequila-nginx

- src: https://github.com/caktus/tequila-django
  version: v0.9.13
  name: tequila-django

- src: https://github.com/caktus/tequila-nodejs
  version: v0.8.0
  name: tequila-nodejs

- src: geerlingguy.nodejs
  version: 4.2.0
  name: nodejs
