# Generated by Django 2.1.3 on 2018-12-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_sound', models.CharField(blank=True, max_length=256)),
                ('fn_trans', models.CharField(blank=True, max_length=256)),
                ('project', models.CharField(blank=True, max_length=64)),
                ('uid', models.CharField(blank=True, max_length=64)),
                ('filepast', models.CharField(blank=True, max_length=64)),
                ('folder', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('wordcount', models.CharField(blank=True, max_length=64)),
                ('encyxref', models.CharField(blank=True, max_length=64)),
                ('encyref2', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('lg_var', models.CharField(blank=True, max_length=64)),
                ('lg_code', models.CharField(blank=True, max_length=8)),
                ('lgvil', models.CharField(blank=True, max_length=64)),
                ('lg_mpio', models.CharField(blank=True, max_length=64)),
                ('lg_state', models.CharField(blank=True, max_length=64)),
                ('lg_country', models.CharField(blank=True, max_length=64)),
                ('recordby', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('tracks', models.CharField(blank=True, max_length=64)),
                ('rec_format', models.CharField(blank=True, max_length=64)),
                ('rec_orig', models.CharField(blank=True, max_length=64)),
                ('rec_machine', models.CharField(blank=True, max_length=64)),
                ('rec_mike', models.CharField(blank=True, max_length=64)),
                ('rec_power', models.CharField(blank=True, max_length=64)),
                ('contr1', models.CharField(blank=True, max_length=64)),
                ('con1_role', models.CharField(blank=True, max_length=64)),
                ('con1_sex', models.CharField(blank=True, max_length=64)),
                ('con1_origin', models.CharField(blank=True, max_length=64)),
                ('con1_track', models.CharField(blank=True, max_length=64)),
                ('contr2', models.CharField(blank=True, max_length=64)),
                ('con2_role', models.CharField(blank=True, max_length=64)),
                ('con2_sex', models.CharField(blank=True, max_length=64)),
                ('con2_origin', models.CharField(blank=True, max_length=64)),
                ('con2_track', models.CharField(blank=True, max_length=64)),
                ('genre', models.CharField(blank=True, max_length=64)),
                ('subgenre', models.CharField(blank=True, max_length=64)),
                ('titnative', models.CharField(blank=True, max_length=64)),
                ('titspn', models.CharField(blank=True, max_length=64)),
                ('titeng', models.CharField(blank=True, max_length=64)),
                ('descrip', models.TextField(blank=True)),
                ('native_prim', models.CharField(blank=True, max_length=64)),
                ('sci_prim', models.CharField(blank=True, max_length=64)),
                ('sci_second', models.CharField(blank=True, max_length=64)),
                ('transby', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('rights', models.CharField(blank=True, max_length=64)),
                ('calidad', models.CharField(blank=True, max_length=64)),
                ('archive', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ref', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
